(setq ctl (acall 'ctl_open ('default nil)))
(setq ctl (car (cdr ctl)))
(setq hctl (acall 'hctl_open_ctl ctl))
(setq hctl (car (cdr hctl)))
(setq hctl (acall 'hctl_close hctl))

(setq hctl (acall 'hctl_open ('default nil)))
(if (= (car hctl) 0)
  (progn
    (princ "open success: " hctl "\n")
    (setq hctl (car (cdr hctl)))
    (princ "open hctl: " hctl "\n")
    (setq hctl (acall 'hctl_close hctl))
    (if (= hctl 0)
      (princ "close success\n")
      (princ "close failed: " hctl "\n")
    )
  )
  (progn
    (princ "open failed: " hctl "\n")
  )
)

(setq ctl (acall 'ctl_open ('default nil)))
(if (= (car ctl) 0)
  (progn
    (princ "ctl open success: " ctl "\n")
    (setq ctl (car (cdr ctl)))
    (setq hctl (acall 'hctl_open_ctl ctl))
    (if (= (car hctl) 0)
      (progn
        (princ "hctl open success: " hctl "\n")
        (setq hctl (car (cdr hctl)))
        (princ "open hctl: " hctl "\n")
        (setq hctl (acall 'hctl_close hctl))
        (if (= hctl 0)
          (princ "hctl close success\n")
          (princ "hctl close failed: " hctl "\n")
        )
      )
      (progn
        (princ "hctl open failed: " ctl "\n")
      )
    )
  )
  (progn
    (princ "ctl open failed: " ctl "\n")
  )
)
