#!/bin/bash

rm -f libtool ltmain.sh config.guess config.sub
aclocal $ACLOCAL_FLAGS
autoheader
automake --foreign --copy --add-missing
autoconf
export CFLAGS='-O2 -Wall -W -pipe -g'
echo "CFLAGS=$CFLAGS"
echo "./configure $@"
./configure $@
unset CFLAGS
make
