/*
 *  Global defines
 */

#define SND_DEV_TYPE_PCM	0
#define SND_DEV_TYPE_CONTROL	1
#define SND_DEV_TYPE_RAWMIDI	2
#define SND_DEV_TYPE_TIMER	3
#define SND_DEV_TYPE_HWDEP	4
#define SND_DEV_TYPE_SEQ	5

#define SND_TRANSPORT_TYPE_SHM	0
#define SND_TRANSPORT_TYPE_TCP	1

